version: "3.8"

services:
  postgres:
    image: arm64v8/postgres:17.4-alpine
    container_name: graphql-poc-postgres
    environment:
      POSTGRES_DB: graphql_poc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - graphql-poc
    volumes:
      - graphql-poc-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  graphql-poc:
    driver: bridge

volumes:
  graphql-poc-data: